from __future__ import annotations
from abc import ABC, abstractmethod
from typing import TypeVar
from app.domains.backoffice.dto import (
    ActualDTO, AdapterCapabilities, AdapterHealth, AssetDTO, BudgetDTO,
    CommitmentDTO, CostCentreDTO, CustomerDTO, ItemDTO, MaintenanceDTO,
    OpportunityDTO, ProjectDTO, PurchaseOrderDTO, ReceiptDTO, StockDTO,
    SupplierDTO, TaskDTO, TimesheetDTO,
)

T = TypeVar("T")


class BackofficePort(ABC):
    """Async anti-corruption boundary shared by local and ERPNext profiles."""
    @abstractmethod
    async def capabilities(self) -> AdapterCapabilities: ...
    @abstractmethod
    async def health(self) -> AdapterHealth: ...
    @abstractmethod
    async def list_items(self) -> list[ItemDTO]: ...
    @abstractmethod
    async def upsert_item(self, item: ItemDTO) -> ItemDTO: ...
    @abstractmethod
    async def list_suppliers(self) -> list[SupplierDTO]: ...
    @abstractmethod
    async def list_purchase_orders(self) -> list[PurchaseOrderDTO]: ...
    @abstractmethod
    async def list_receipts(self) -> list[ReceiptDTO]: ...
    @abstractmethod
    async def list_stock(self) -> list[StockDTO]: ...
    @abstractmethod
    async def list_customers(self) -> list[CustomerDTO]: ...
    @abstractmethod
    async def list_opportunities(self) -> list[OpportunityDTO]: ...
    @abstractmethod
    async def list_projects(self) -> list[ProjectDTO]: ...
    @abstractmethod
    async def list_tasks(self) -> list[TaskDTO]: ...
    @abstractmethod
    async def list_timesheets(self) -> list[TimesheetDTO]: ...
    @abstractmethod
    async def list_assets(self) -> list[AssetDTO]: ...
    @abstractmethod
    async def list_maintenance(self) -> list[MaintenanceDTO]: ...
    @abstractmethod
    async def list_cost_centres(self) -> list[CostCentreDTO]: ...
    @abstractmethod
    async def list_budgets(self) -> list[BudgetDTO]: ...
    @abstractmethod
    async def list_commitments(self) -> list[CommitmentDTO]: ...
    @abstractmethod
    async def list_actuals(self) -> list[ActualDTO]: ...
