"""qms: units, genealogy, protocols, non-conformance

Revision ID: 0004_qms
Revises: 0003_ecm
Created: 2026-08-09 18:06:42.789682
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = "0004_qms"
down_revision: str | None = "0003_ecm"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_protocols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applies_to_part_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'revision', name='uq_protocol_revision')
    )
    op.create_index(op.f('ix_test_protocols_code'), 'test_protocols', ['code'], unique=False)
    op.create_table('test_spec_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['test_protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'metric', name='uq_spec_metric')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('built_to_revision_id', sa.UUID(), nullable=True),
    sa.Column('as_built_baseline_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('In production', 'In test', 'Shipped', 'In field', 'Returned', 'Scrapped', name='unit_status', native_enum=False, length=16), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plant', sa.String(length=64), nullable=True),
    sa.Column('customer_ref', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['as_built_baseline_id'], ['configuration_baselines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['built_to_revision_id'], ['part_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_part_id'), 'units', ['part_id'], unique=False)
    op.create_index(op.f('ix_units_serial_number'), 'units', ['serial_number'], unique=True)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.create_table('non_conformances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('Incoming inspection', 'In process', 'Final test', 'Field', name='ncr_source', native_enum=False, length=24), nullable=False),
    sa.Column('severity', sa.Enum('Minor', 'Major', 'Critical', name='ncr_severity', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Contained', 'Dispositioned', 'Closed', name='ncr_status', native_enum=False, length=16), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('part_id', sa.UUID(), nullable=True),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('disposition', sa.Enum('Pending', 'Use as is', 'Rework', 'Scrap', 'Return to supplier', name='ncr_disposition', native_enum=False, length=24), nullable=False),
    sa.Column('disposition_note', sa.Text(), nullable=True),
    sa.Column('raised_by', sa.UUID(), nullable=True),
    sa.Column('raised_by_label', sa.String(length=128), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_ecr_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ncr_status', 'non_conformances', ['status', 'raised_at'], unique=False)
    op.create_index(op.f('ix_non_conformances_escalated_ecr_id'), 'non_conformances', ['escalated_ecr_id'], unique=False)
    op.create_index(op.f('ix_non_conformances_lot_number'), 'non_conformances', ['lot_number'], unique=False)
    op.create_index(op.f('ix_non_conformances_number'), 'non_conformances', ['number'], unique=True)
    op.create_table('unit_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('part_revision_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=16), nullable=False),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('supplier_lot', sa.String(length=64), nullable=True),
    sa.Column('child_serial_number', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('operation_seq', sa.Integer(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['part_revision_id'], ['part_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unit_component_lot', 'unit_components', ['lot_number'], unique=False)
    op.create_index('ix_unit_component_part', 'unit_components', ['part_id'], unique=False)
    op.create_index('ix_unit_component_unit', 'unit_components', ['unit_id', 'position'], unique=False)
    op.create_index(op.f('ix_unit_components_child_serial_number'), 'unit_components', ['child_serial_number'], unique=False)
    op.create_table('capa_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('non_conformance_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('Corrective', 'Preventive', name='capa_kind', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_label', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effectiveness_check', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['non_conformance_id'], ['non_conformances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_actions_non_conformance_id'), 'capa_actions', ['non_conformance_id'], unique=False)
    # ----------------------------------------------------------------------
    # Test records move from a serial *string* to a real unit.
    # ----------------------------------------------------------------------
    # `unit_id` arrives nullable so the statement succeeds against rows that
    # already exist, is backfilled from the serial numbers those rows carry, and
    # is only then made mandatory. Adding it non-null outright would fail on any
    # database that has ever recorded a measurement.
    op.add_column('lab_test_records', sa.Column('unit_id', sa.UUID(), nullable=True))
    op.add_column('lab_test_records', sa.Column('protocol_id', sa.UUID(), nullable=True))
    op.add_column(
        'lab_test_records',
        sa.Column(
            'result',
            sa.Enum('Pass', 'Fail', 'Not evaluated', name='test_result',
                    native_enum=False, length=16),
            nullable=False,
            server_default='Not evaluated',
        ),
    )
    op.add_column('lab_test_records', sa.Column('breaches', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # One unit per distinct serial that has ever been measured. `part_id` on the
    # old rows was a convenience join; it becomes the unit's identity.
    op.execute(
        """
        INSERT INTO units (id, serial_number, part_id, status, built_at, created_at)
        SELECT
            gen_random_uuid(),
            ltr.serial_number,
            COALESCE(ltr.part_id, (SELECT id FROM parts ORDER BY part_number LIMIT 1)),
            'In test',
            MIN(ltr.recorded_at),
            now()
        FROM lab_test_records ltr
        GROUP BY ltr.serial_number, ltr.part_id
        """
    )
    op.execute(
        """
        UPDATE lab_test_records ltr
        SET unit_id = u.id
        FROM units u
        WHERE u.serial_number = ltr.serial_number
        """
    )
    # Any row that still has no unit has a serial no unit could be built for,
    # which should be impossible. Fail loudly rather than dropping the column
    # that would let anyone work out what happened.
    op.execute(
        """
        DO $$
        DECLARE orphaned int;
        BEGIN
            SELECT count(*) INTO orphaned FROM lab_test_records WHERE unit_id IS NULL;
            IF orphaned > 0 THEN
                RAISE EXCEPTION
                    'Refusing to continue: % test record(s) could not be matched to a unit.',
                    orphaned;
            END IF;
        END $$;
        """
    )
    op.alter_column('lab_test_records', 'unit_id', nullable=False)
    op.alter_column('lab_test_records', 'result', server_default=None)

    op.drop_index(op.f('ix_lab_serial_time'), table_name='lab_test_records')
    op.drop_index(op.f('ix_lab_test_records_serial_number'), table_name='lab_test_records')
    op.create_index(op.f('ix_lab_test_records_result'), 'lab_test_records', ['result'], unique=False)
    op.create_index(op.f('ix_lab_test_records_unit_id'), 'lab_test_records', ['unit_id'], unique=False)
    op.create_index('ix_lab_unit_time', 'lab_test_records', ['unit_id', 'recorded_at'], unique=False)
    op.drop_constraint(op.f('lab_test_records_part_id_fkey'), 'lab_test_records', type_='foreignkey')
    # Named explicitly. Autogenerate emits `None` here and lets PostgreSQL pick,
    # which leaves the downgrade with no name to drop by — it fails with
    # "Can't emit DROP CONSTRAINT ... it has no name".
    op.create_foreign_key(
        'fk_lab_test_records_protocol', 'lab_test_records', 'test_protocols',
        ['protocol_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_lab_test_records_unit', 'lab_test_records', 'units',
        ['unit_id'], ['id'], ondelete='CASCADE',
    )
    op.drop_column('lab_test_records', 'part_id')
    op.drop_column('lab_test_records', 'serial_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The serial and the part come back from the unit the record now points at,
    # before that pointer is dropped. Added nullable and tightened afterwards,
    # for the same reason `unit_id` was on the way up.
    op.add_column('lab_test_records', sa.Column('serial_number', sa.VARCHAR(length=64), nullable=True))
    op.add_column('lab_test_records', sa.Column('part_id', sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE lab_test_records ltr
        SET serial_number = u.serial_number,
            part_id       = u.part_id
        FROM units u
        WHERE u.id = ltr.unit_id
        """
    )
    op.alter_column('lab_test_records', 'serial_number', nullable=False)

    op.drop_constraint('fk_lab_test_records_unit', 'lab_test_records', type_='foreignkey')
    op.drop_constraint('fk_lab_test_records_protocol', 'lab_test_records', type_='foreignkey')
    op.create_foreign_key(op.f('lab_test_records_part_id_fkey'), 'lab_test_records', 'parts', ['part_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_lab_unit_time', table_name='lab_test_records')
    op.drop_index(op.f('ix_lab_test_records_unit_id'), table_name='lab_test_records')
    op.drop_index(op.f('ix_lab_test_records_result'), table_name='lab_test_records')
    op.create_index(op.f('ix_lab_test_records_serial_number'), 'lab_test_records', ['serial_number'], unique=False)
    op.create_index(op.f('ix_lab_serial_time'), 'lab_test_records', ['serial_number', 'recorded_at'], unique=False)
    op.drop_column('lab_test_records', 'breaches')
    op.drop_column('lab_test_records', 'result')
    op.drop_column('lab_test_records', 'protocol_id')
    op.drop_column('lab_test_records', 'unit_id')
    op.drop_index(op.f('ix_capa_actions_non_conformance_id'), table_name='capa_actions')
    op.drop_table('capa_actions')
    op.drop_index(op.f('ix_unit_components_child_serial_number'), table_name='unit_components')
    op.drop_index('ix_unit_component_unit', table_name='unit_components')
    op.drop_index('ix_unit_component_part', table_name='unit_components')
    op.drop_index('ix_unit_component_lot', table_name='unit_components')
    op.drop_table('unit_components')
    op.drop_index(op.f('ix_non_conformances_number'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_lot_number'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_escalated_ecr_id'), table_name='non_conformances')
    op.drop_index('ix_ncr_status', table_name='non_conformances')
    op.drop_table('non_conformances')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_units_serial_number'), table_name='units')
    op.drop_index(op.f('ix_units_part_id'), table_name='units')
    op.drop_table('units')
    op.drop_table('test_spec_limits')
    op.drop_index(op.f('ix_test_protocols_code'), table_name='test_protocols')
    op.drop_table('test_protocols')
    # ### end Alembic commands ###
