"""ecm: change requests, board reviews, orders, notices

Revision ID: 0003_ecm
Revises: 0002_pdm_depth
Created: 2026-08-09 16:34:06.390919
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = "0003_ecm"
down_revision: str | None = "0002_pdm_depth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('preliminary_impact', sa.Text(), nullable=True),
    sa.Column('originator_id', sa.UUID(), nullable=True),
    sa.Column('originator_label', sa.String(length=128), nullable=False),
    sa.Column('origin', sa.Enum('R&D', 'Supply chain', 'Quality', 'Field', 'Cost reduction', 'Regulatory', name='change_origin', native_enum=False, length=24), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Normal', 'High', 'Urgent', name='change_priority', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Under review', 'Approved', 'Rejected', 'Converted', 'Cancelled', name='ecr_status', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_number'), 'change_requests', ['number'], unique=True)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_table('change_affected_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_request_id', 'part_id', name='uq_affected_item')
    )
    op.create_table('change_board_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('seat', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_label', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.Enum('Approve', 'Reject', 'Abstain', 'Request info', name='review_decision', native_enum=False, length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_request_id', 'seat', name='uq_ccb_seat_vote')
    )
    op.create_index(op.f('ix_change_board_reviews_change_request_id'), 'change_board_reviews', ['change_request_id'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('disposition', sa.Text(), nullable=False),
    sa.Column('effectivity_type', sa.Enum('As soon as possible', 'On a date', 'From a serial number', name='effectivity_type', native_enum=False, length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('effective_serial', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Released', 'Cancelled', name='eco_status', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_orders_number'), 'change_orders', ['number'], unique=True)
    op.create_index(op.f('ix_change_orders_status'), 'change_orders', ['status'], unique=False)
    op.create_table('impact_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_assessments_change_request_id'), 'impact_assessments', ['change_request_id'], unique=False)
    op.create_table('change_notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('change_order_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_notices_number'), 'change_notices', ['number'], unique=True)
    op.create_table('change_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_order_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('Add component', 'Remove component', 'Change quantity', 'Replace component', 'Revise attributes', name='change_action', native_enum=False, length=24), nullable=False),
    sa.Column('parent_part_id', sa.UUID(), nullable=False),
    sa.Column('child_part_id', sa.UUID(), nullable=True),
    sa.Column('new_child_part_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('find_number', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_child_part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eco_line_order', 'change_order_lines', ['change_order_id', 'sequence'], unique=False)
    op.create_table('change_notice_acknowledgements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=64), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['change_notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'recipient', name='uq_notice_ack')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_notice_acknowledgements')
    op.drop_index('ix_eco_line_order', table_name='change_order_lines')
    op.drop_table('change_order_lines')
    op.drop_index(op.f('ix_change_notices_number'), table_name='change_notices')
    op.drop_table('change_notices')
    op.drop_index(op.f('ix_impact_assessments_change_request_id'), table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_index(op.f('ix_change_orders_status'), table_name='change_orders')
    op.drop_index(op.f('ix_change_orders_number'), table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_change_board_reviews_change_request_id'), table_name='change_board_reviews')
    op.drop_table('change_board_reviews')
    op.drop_table('change_affected_items')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_number'), table_name='change_requests')
    op.drop_table('change_requests')
    # ### end Alembic commands ###
